### ISSUE TITLE
 @ symbol module "Error: Cannot find module"

### ISSUE THREAD

**Issue by serbasii** [ntsaini/node-red-contrib-function-npm#11]
when '@ symbol' modules are downloading, occurs error, Cannot find module 'C:\Users\User1\AppData\Local\Temp\d-119017-15432-1on0lc3.qc91/node_modules/'"

**Comment by ntsaini** [comment]
@serbasii not sure what you are referring to. Can you give a concrete example to replicate the error?

**Comment by serbasii** [comment]
not to be all scoped packages maybe try to @aspnet/signalr package.

**Comment by ntsaini** [comment]
Ok, I understand now. That happens because I am using the @ character as a separator for specifying the version info. but since some packages can be named with "@" symbol as well the script wouldn't be able to parse those correctly.

Thanks for bringing it to my attention I have think about how I want to fix it without breaking the versioning specifier.

**Comment by ntsaini** [comment]
@serbasii fixed the issue in the new release. Try it out.

**Comment by serbasii** [comment]
works great! thanks

**Comment by ntsaini** [comment]
Cool, closing the issue then.
