### ISSUE TITLE
Previous instances keep running

### ISSUE THREAD

**Issue by battosai30** [ntsaini/node-red-contrib-function-npm#9]
Hi,

First thanks for your job, it's very cool !

I have a little issue, and as I'm not a Node.js expert, the problem may comes from my code. I'm just trying to play with noble library to listen to bluetooth iBeacon dongle. I just want to build a nodered function that scan for iBeacons and send a message when an advertisement comes. But when I re-deploy my flow, it's like a new instance is created and I get output from my previous deploys (I don't know if I'm clear ...). If I tell it in another way : on a fresh restart nodered I deploy my code. I get one message per advertisement. I re-deploy it : now I get two message for the same advertisement. If I redeploy it : 3 messages etc ...

The code : 

```
let noble = require('noble');

noble.startScanning([], true);

noble.on('discover', function(peripheral) {
    
let macAddress = peripheral.uuid;
let rssi = peripheral.rssi;
let localName = peripheral.advertisement.localName;
//console.log('found device: ', macAddress, ' ', localName, ' ', rssi);
let result=macAddress +' ' +rssi + ' ' +localName;
    node.send({payload:result});
    
});

node.on('close', function() {
    noble.stopScanning();
    noble = null;
});

return;
```

![image](https://user-images.githubusercontent.com/5184702/47549575-ca2b6580-d8fc-11e8-8c1f-85e47bacb509.png)

So if you can point where is the problem I would be thankful :)

Regards

**Comment by ntsaini** [comment]
Hey @battosai30 

Thanks for submitting the issue. At first glance I don't think it is cause by the npm node. 

It seems that the event subscription on this line `noble.on('discover', function(peripheral)` is not getting cleared for some reason. Thus when you redploy you have both new and old subscriptions.

I haven't really used the noble library but this might be a question for them. One suggestion I can offer is to put some logging in your `node.on('close')` function using node.log and see if it is actually stopping the scan. I am assuming stop scan should clear all event subscriptions but it might not be the case so that is another avenue to look into.

Please update the issue with what you find.

Thanks

**Comment by battosai30** [comment]
Thanks for your answer.

I keep you in touch ;)

**Comment by battosai30** [comment]
Got it !

Thanks to node-red-contrip-noble lib (which I will use as it's exactly what I wanted to do), I look at his code and there is two things to do to avoid my troubles : 
- Use removeAllListeners() to as you suggested to suspend events.
- Use a flag to know if it's already scanning or not because if like in my simple flow you click severall time on the inject node, it will instance many listeners and the problem is back.

So finally my code corrected but only for the first point (but I highly recommend to use node-red-contrib-ble which is far away better) : 
```
let noble = require('noble');

noble.startScanning([], true);

noble.on('discover', function(peripheral) {
    
let macAddress = peripheral.uuid;
let rssi = peripheral.rssi;
let localName = peripheral.advertisement.localName;
//console.log('found device: ', macAddress, ' ', localName, ' ', rssi);
let result=macAddress +' ' +rssi + ' ' +localName;
    node.send({payload:result});
    
});

node.on('close', function() {
    noble.stopScanning();
    noble.removeAllListeners();
    noble = null;
});

return;
```
Thanks for your time !
